[programs.localnet]
cpi_examples = "DAo2pDtpiBFDu4TTiv2WggP6PfQ6FnKqwSRYxpMjyuV2"

[provider]
cluster = "localnet"
wallet = "/Users/alexwlezien/.config/solana/id.json"

[[test.genesis]]
address = "DAo2pDtpiBFDu4TTiv2WggP6PfQ6FnKqwSRYxpMjyuV2"
program = "target/deploy/cpi_examples.so"

[[test.genesis]]
address = "VoLT1mJz1sbnxwq5Fv2SXjdVDgPXrb9tJyC8WpMDkSp"
program = "dumps/volt.so"

# Serum Mainnet
[[test.genesis]]
address = "9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin"
program = "dumps/serum.so"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test_deposit.ts"
